banquet/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib import admin

import api
from views import *

admin.autodiscover()

urlpatterns = patterns('',

    # Динамические страницы:
    url(r'^$', IndexPage.as_view()),
    url(r'^kitchen/', include(admin.site.urls)),
    url(r'^import/$', ImportView.as_view()),
    url(r'^orders/$', OrderPage.as_view()),
    url(r'^orders/(?P<number>\w+)/$', OrderPage.as_view()),
    url(r'^orders/(?P<number>\w+)/(?P<status>%s)/$' % '|'.join(Order.STATUSES.keys()), OrderPage.as_view()),
    url(r'^menu/$', MenuPage.as_view()),
    url(r'^dishes/(?P<pk>\d+)/$', DishPage.as_view()),
    url(r'^products/$', ProductList.as_view()),
    url(r'^products/(?P<pk>\d+)/$', ProductDetails.as_view()),
    url(r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),

    # API
    url(r'^api/groups/$', api.ListDishGroups.as_view()),
    url(r'^api/servings/$', api.LibServings.as_view()),
    url(r'^api/dishes/$', api.DishList.as_view()),
    url(r'^api/dishes/(?P<pk>\d+)/$', api.DishDetails.as_view()),
    url(r'^api/products/(?P<pk>\d+)/$', api.ProductDetails.as_view()),
    url(r'^api/orders/$', api.Orders.as_view()),

    # Все остальное
    url(r'^(?P<slug>\w+)/$', StaticPage.as_view()),
)


if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

banquet/models.py
# -*- coding: utf-8 -*-
import random
import string

from decimal import Decimal
from collections import OrderedDict

from django.db import models
from django.dispatch import receiver
from django.core.mail import send_mail
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save, post_save
from django.contrib.sessions.models import Session
from sorl.thumbnail import ImageField

from utils.managers import OnlyActives
from utils.files import *


LIBRARY_TAGS_SERVING = {
    'canape': 'канапе',
    'roll': 'ролл',
    'short': 'в шоте',
    'skewer': 'на шпажке',
    'spoon': 'на ложечке',
    'tartlet': 'тарталетка',
    'volauvent': 'в волаване',
}


def generate_number(n=None):
    """
    Генерация номера заказа
    """
    n = n or 8
    return ''.join(random.SystemRandom().choice(string.uppercase + string.digits) for _ in xrange(n)).upper()


class CatalogueItem(models.Model):
    """
    Позиция в каталоге
    """
    title = models.CharField(max_length=255, verbose_name=u'заголовок')
    desc = models.TextField(blank=True, null=True, verbose_name=u'описание')
    image = models.ImageField(upload_to=upload_as_uuid, blank=True, verbose_name=u'фото')
    price = models.PositiveIntegerField(verbose_name=u'цена', help_text=u'руб.')

    class Meta:
        abstract = True

    def __unicode__(self):
        return self.title

    def str_price(self):
        return '%s руб.' % self.price

    def str_weight(self):
        return '%s гр.' % self.get_total_weight()

    def get_absolute_url(self):
        return reverse('%s.views.details' % self.__class__.__name__.lower(), args=[str(self.id)])

    str_price.short_description = 'Цена'
    str_weight.short_description = 'Вес'


class Page(models.Model):
    """
    Раздел сайта
    """
    title = models.CharField(max_length=50, unique=True, verbose_name=u'заголовок страницы')
    slug = models.SlugField(blank=False, verbose_name=u'короткое имя')
    html = models.TextField(blank=True, verbose_name=u'текст страницы')
    image = models.ImageField(upload_to=upload_as_uuid, blank=True, verbose_name=u'изображение')
    redirect = models.URLField(blank=True, verbose_name=u'переадресация')
    tpl_file = models.FileField(upload_to=upload_as_template, blank=True, verbose_name=u'шаблон страницы')
    is_active = models.BooleanField(default=True, verbose_name=u'доступен на сайте')
    queue = models.PositiveIntegerField(default=0, verbose_name=u'порядок сортировки')

    class Meta:
        verbose_name = u'страница сайта'
        verbose_name_plural = u'страницы сайта'

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return '/%s/' % self.slug


class Collection(models.Model):
    """
    Коллекция (стиль накрытия)
    """
    title = models.CharField(max_length=255, verbose_name=u'заголовок')
    desc = models.TextField(blank=True, null=True, verbose_name=u'описание')
    image = models.ImageField(upload_to=upload_as_uuid, blank=True, verbose_name=u'фото')

    class Meta:
        verbose_name = u'коллекция'
        verbose_name_plural = u'коллекции'

    def __unicode__(self):
        return self.title

    def get_absolute_url(self):
        return '/collections/%d/' % self.id


class EventType(models.Model):
    """
    Тип мероприятия
    """
    title = models.CharField(max_length=50, unique=True, verbose_name=u'заголовок мероприятия')
    image = models.ImageField(upload_to=upload_as_uuid, blank=True, verbose_name=u'изображение')
    html = models.TextField(blank=True, verbose_name=u'текст страницы')
    added = models.DateTimeField(auto_now_add=True, verbose_name=u'дата создания')
    changed = models.DateTimeField(auto_now=True, verbose_name=u'дата изменения')
    is_active = models.BooleanField(default=True, verbose_name=u'доступен на сайте')

    class Meta:
        verbose_name = u'мероприятие'
        verbose_name_plural = u'типы мероприятий'

    def __unicode__(self):
        return self.title


class IngredientType(models.Model):
    """
    Тип ингридиента
    """
    title = models.CharField(max_length=50, unique=True)
    is_active = models.BooleanField(default=True, verbose_name=u'доступно на сайте')

    class Meta:
        verbose_name = u'тип блюда'
        verbose_name_plural = u'типы блюд по содержанию'

    def __unicode__(self):
        return self.title


class Ingredient(models.Model):
    """
    Ингредиент блюда
    """
    title = models.CharField(max_length=100, unique=True, verbose_name=u'заголовок')

    class Meta:
        verbose_name = u'ингредиент'
        verbose_name_plural = u'справочник ингредиентов'

    def __unicode__(self):
        return self.title


class DishGroup(models.Model):
    """
    Группа блюд (холодные закуски, горячее, десерты и т.п.)
    """
    parent = models.ForeignKey('self', blank=True, null=True, verbose_name=u'входит в')
    title = models.CharField(max_length=255, unique=True, verbose_name=u'заголовок')
    desc = models.TextField(blank=True, verbose_name=u'описание')
    is_active = models.BooleanField(default=True, verbose_name=u'доступно на сайте')

    class Meta:
        verbose_name = u'группа блюд'
        verbose_name_plural = u'справочник групп блюд'

    def __unicode__(self):
        return self.title


class Dish(CatalogueItem):
    """
    Блюдо
    """
    group = models.ForeignKey('DishGroup', related_name='dishes', verbose_name=u'группа блюд')
    events = models.ManyToManyField('EventType', blank=True, related_name='dishes', verbose_name=u'тип мероприятия')
    serving = models.CharField(max_length=32, default=None, null=True, blank=True, choices=LIBRARY_TAGS_SERVING.items(), verbose_name=u'подача')
    dish_types = models.ManyToManyField('IngredientType', blank=True, verbose_name=u'относится к блюдам типа')
    ingredients = models.ManyToManyField('Ingredient', through='DishIngredients', verbose_name=u'ингредиенты')
    total_weight = models.PositiveIntegerField(default=0, verbose_name=u'общий вес', help_text=u'грамм')
    is_active = models.BooleanField(default=True, verbose_name=u'вкл.')

    class Meta:
        ordering = ['title']
        verbose_name = u'блюдо'
        verbose_name_plural = u'блюда'

    def get_total_weight(self):
        return self.total_weight if self.total_weight else sum(DishIngredients.objects.filter(dish__id=self.id).values_list('ingredient_weight', flat=True))

    def str_ingredients(self):
        return ', '.join([x.title.lower() for x in self.ingredients.all()])

    def str_exit(self):
        return '/'.join([str(x) for x in DishIngredients.objects.filter(dish__id=self.id).values_list('ingredient_weight', flat=True) if x])

    def str_serving(self):
        return LIBRARY_TAGS_SERVING.get(self.serving, '')

    def qty_ordered(self):
        return sum(x.qty for x in self.ordereddishes_set.all())

    def get_absolute_url(self):
        return '/dishes/%d/' % self.id

    str_ingredients.short_description = 'Ингредиенты'
    str_exit.short_description = 'Выход'


class DishSetItem(models.Model):
    """
    Блюдо, закрепленное за сетом
    """
    dish = models.ForeignKey('Dish', verbose_name=u'блюдо')
    dish_set = models.ForeignKey('DishSet', verbose_name=u'сет')
    dish_qty = models.PositiveIntegerField(default=1, verbose_name=u'количество блюд в сете', help_text=u'шт')


class DishSet(CatalogueItem):
    """
    Набор блюд
    """
    group = models.ForeignKey('DishGroup', related_name='dishsets', verbose_name=u'группа блюд')
    dishes = models.ManyToManyField('Dish', through='DishSetItem', verbose_name=u'включает блюда')
    is_active = models.BooleanField(default=True, verbose_name=u'вкл.')

    class Meta:
        ordering = ['title']
        verbose_name = u'Блюдо-сет'
        verbose_name_plural = u'Блюдо-сеты'

    def get_total_weight(self):
        items_qty = {x.dish.id: x.dish_qty for x in self.dishsetitem_set.all()}
        return sum((x.get_total_weight() * items_qty.get(x.id, 0))  for x in self.dishes.all())

    def str_ingredients(self):
        ingredients = set()
        for dish in self.dishes.all():
            ingredients |= set(dish.ingredients.all())
        return ', '.join([x.title.lower() for x in ingredients])

    def str_exit(self):
        return '/'.join([str(x.total_weight) for x in self.dishes.all()])


class DishIngredients(models.Model):
    """
    Ингредиенты блюда
    """
    dish = models.ForeignKey('Dish', verbose_name=u'блюдо')
    ingredient = models.ForeignKey('Ingredient', verbose_name=u'ингредиент')
    ingredient_weight = models.PositiveIntegerField(default=0, verbose_name=u'вес ингредиента', help_text=u'грамм')

    class Meta:
        # auto_created = True
        verbose_name = u'ингредиент блюда'
        verbose_name_plural = u'ингредиенты блюда'

    def __unicode__(self):
        return u'%s в %s' % (self.ingredient.title, self.dish.title)


class DishBind(models.Model):
    """
    Привязка блюда
    """
    dish = models.ForeignKey('Dish', blank=False, verbose_name=u'блюдо')
    qty = models.PositiveIntegerField(default=1, verbose_name=u'количество')

    class Meta:
        abstract = True
        verbose_name = u'связь с блюдом'
        verbose_name_plural = u'прикоепленные блюда'

    def __unicode__(self):
        return ''

    @property
    def cost(self):
        return self.dish.price * self.qty


class InProduct(DishBind):
    """ Блюдо в продукте """
    product = models.ForeignKey('Product', blank=True, null=True, verbose_name=u'готовое предложение')


class InOrder(DishBind):
    """ Блюдо в заказе """
    order = models.ForeignKey('Order', blank=True, null=True, verbose_name=u'заказ')


class OrderProduct(models.Model):
    """
    Базовый класс для формирования готового предложения и заказа
    """
    image = models.ImageField(upload_to=upload_as_uuid, blank=True, verbose_name=u'изображение')

templates/about.html
{% extends "static.html" %}
{% load thumbnail %}


{% block root_section %}
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <h2>Наша компания</h2>
                <figure><img src="http://livedemo00.template-help.com/wt_48629/img/page2_pic1.jpg" /></figure>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                </p>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                </p>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                <h2>Наша миссия</h2>
                <p>
                    <i class="fa-comment"></i> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                </p>
                <h3>Наша миссия</h3>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                </p>
                <h3>Наша миссия</h3>
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                </p>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-12 hidden-xs">
                <h2>Наша жизнь</h2>
                <div class="row hr">
                    <figure class="col-lg-6 col-sm-6"><a href="#"><img src="http://livedemo00.template-help.com/wt_48629/img/page2_pic2.jpg" /></a></figure>
                    <figure class="col-lg-6 col-sm-6"><a href="#"><img src="http://livedemo00.template-help.com/wt_48629/img/page2_pic2.jpg" /></a></figure>
                    <figure class="col-lg-6 col-sm-6"><a href="#"><img src="http://livedemo00.template-help.com/wt_48629/img/page2_pic2.jpg" /></a></figure>
                    <figure class="col-lg-6 col-sm-6"><a href="#"><img src="http://livedemo00.template-help.com/wt_48629/img/page2_pic2.jpg" /></a></figure>
                    <figure class="col-lg-6 col-sm-6"><a href="#"><img src="http://livedemo00.template-help.com/wt_48629/img/page2_pic2.jpg" /></a></figure>
                    <figure class="col-lg-6 col-sm-6"><a href="#"><img src="http://livedemo00.template-help.com/wt_48629/img/page2_pic2.jpg" /></a></figure>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <title>Canapet</title>

    <link rel="icon" href="images/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">
    <meta name="format-detection" content="telephone=no" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css">
    {% block STATIC_STYLE %}<link rel="stylesheet" media="screen" type="text/less" href="{{ style_path }}">{% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/less.js/2.4.0/less.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash-compat/3.3.1/lodash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.12.1/ui-bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular-ui-bootstrap/0.12.1/ui-bootstrap-tpls.min.js"></script>

    <script type="text/javascript" src="{% static 'scripts/libs/angular-locale_ru.js' %}"></script>
    <script type="text/javascript" src="{% static 'scripts/app.js' %}"></script>

    {% block JSTop %}{% endblock %}

    <!--[if (gt IE 9)|!(IE)]><!-->
    <!--<![endif]-->
    <!--[if lt IE 9]>
        <div style='text-align:center'><a href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode"><img src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg" border="0" height="42" width="820" alt="You are using an outdated browser. For a faster, safer browsing experience, upgrade for free today." /></a></div>
      <![endif]-->
      <!--[if lt IE 9]><script src="../docs-assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

      <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
      <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
      <![endif]-->
</head>
<body ng-app="canapp">

    <header class="clearfix">
        <nav class="navbar navbar-static-top">
            <div class="container-fluid">
                <div class="col-lg-3 col-md-3 col-sm-3 navbar-header">
                    <a class="navbar-brand" href="/">Canapet</a>
                </div>
                <div class="collapse navbar-collapse">
                    <menu class="nav navbar-nav">
                        <li{% if slug == 'about' %} class="active"{% endif %}><a href="/about/">О нас</a></li>
                        <li{% if slug == 'menu' %} class="active"{% endif %}><a href="/menu/">Меню</a></li>
                        <li class="dropdown{% if slug == 'products' %} active{% endif %}">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Готовые предложения <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                {% for event in events %}
                                    <li class="dropdown-header">{{ event.title }}</li>
                                        {% for product in products %}
                                            {% if product.event.id == event.id %}
                                                <li><a href="/products/{{ product.id }}/">{{ product.title }}</a></li>
                                            {% endif %}
                                        {% endfor %}
                                    <li class="divider"></li>
                                {% endfor %}
                                {% comment %}<li><a href="/products/">Архив <span class="badge pull-right">{{ products|length }}</span></a></li>{% endcomment %}
                            </ul>
                        </li>
                        <li{% if slug == 'contacts' %} class="active"{% endif %}><a href="/contacts/">Контакты</a></li>
                    </menu>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="badge">{{ orders|length }}</span> Мои заказы <b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                {% for order in orders %}
                                    {% if order.status != 'delivered' %}
                                        <li><a href="/orders/{{ order.number }}/">{{ order.title }}</a></li>
                                    {% endif %}
                                {% endfor %}
                                <li class="divider"></li>
                                <li class="dropdown-header">Последние заказы</li>
                                {% for order in orders %}
                                    {% if order.status == 'delivered' %}
                                        <li><a href="/orders/{{ order.number }}/">{{ order.title }}</a></li>
                                    {% endif %}
                                {% endfor %}
                                <li class="divider"></li>
                                <li><a href="/orders/">Все заказы <span class="badge pull-right">{{ orders|length }}</span></a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <section class="root">
        {% block alerts %}
            <div class="container alerts" ng-controller="globalMessages" ng-show="alerts.length">
                <alert ng-repeat="alert in alerts" type="{$ alert.type $}" close="closeAlert(alert)">{$ alert.msg $}</alert>
            </div>
        {% endblock %}

        {% block root_section %}
            <div class="jumbotron">
                <h3 class="text-center">Здесь должен быть перегружен основной блок с контентом</h3>
            </div>
        {% endblock %}
    </section>

    <footer class="footer">
        <div class="container">
            {% comment %}
            <nav class="navbar navbar-bottom" role="navigation">
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li><a href="/about/">О нас</a></li>
                        <li><a href="/menu/">Меню</a></li>
                        <li><a href="/products/">Готовые предложения</a></li>
                        <li><a href="/contact/">Контакты</a></li>
                    </ul>
                </div>
            </nav>
            {% endcomment %}
        </div>
    </footer>
    {% block JSBottom %}{% endblock %}
    <!-- Yandex.Metrika counter --><script type="text/javascript"> (function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter32224624 = new Ya.Metrika({ id:32224624, clickmap:true, trackLinks:true, accurateTrackBounce:true, webvisor:true, trackHash:true }); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = "https://mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="https://mc.yandex.ru/watch/32224624" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->
</body>
</html>

templates/dish.html
{% extends "base.html" %}
{% load thumbnail %}

{% block root_section %}
    <div class="container">
        <div class="row dish">
            {% thumbnail dish.image "600" crop="center" as img %}
				{{ img.url }}
                <div id="dishImage" class="col-lg-6 col-md-6 col-sm-9 col-xs-9 opacube" style="background-image: url({{ img.url }})"></div>
            {% endthumbnail %}
            <article class="col-lg-6 col-md-6 col-sm-6 col-xs-6 col-lg-offset-6 col-md-offset-6 col-sm-offset-6 col-xs-offset-6">
                <div class="opacube"></div>
                <header class="row">
                    <div class="col-xs-12">
                        <h2>{{ dish.title }}</h2>
                        <a href="/menu/#group{{dish.group.id}}" class="label label-link">{{ dish.group.title }}</a>
                        <a class="label label-default">{{ dish.str_serving }}</a>
                    </div>
                </header>
                <section class="row">
                    <div class="col-xs-12">
                        <p>{{ dish.desc }}</p>
                    </div>
                </section>
                <footer class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 weight">
                        {% if dish.ingredients %}
                            <div class="ingridients">
                                {% for i in dish.dishingredients_set.all %}
                                    {% if not forloop.first %}<span class="sprt">/</span>{% endif %}
                                    <span class="weight" data-toggle="tooltip" data-placement="top" title="{{ i.ingredient.title }}">{{ i.ingredient_weight }}</span>
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                    <div class="col-lg-6 col-md-5 col-sm-6 col-xs-5">
                        <div class="pull-right">
                            {% if orders %}
                                <div class="btn-group">
                                    <button type="button" class="btn btn-success">Добавить к заказу</button>
                                    <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                        <span class="caret"></span>
                                    </button>

                                    <ul class="dropdown-menu" role="menu">
                                        {% for order in orders %}
                                            {% if dish not in order.dishes.all %}
                                                <li><a href="/orders/{{ order.number }}/">{{ order.title }}</a></li>
                                            {% endif %}
                                        {% endfor %}
                                    </ul>
                                </div>
                            {% else %}
                                <button type="button" class="btn btn-success">Заказать блюдо</button>
                            {% endif %}
                        </div>
                    </div>
                </footer>
                {% comment %}
                {% if prod %}
                    <div class="row">
                        {% for p in prod %}
                            <div class="col-lg-4 col-md-4 col-sm-2 col-xs-2">
                                <div class="thumbnail">
                                    {% thumbnail p.image "200x200" crop="center" as img %}
                                        <a href="/products/{{ p.id }}/"><img src="{{ img.url }}"></a>
                                    {% endthumbnail %}
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
                {% endcomment %}
            </article>
        </div>
    </div>
{% endblock %}

{% block JSBottom %}
    <script>$("[data-toggle=\"tooltip\"]").tooltip()</script>
{% endblock %}

templates/import.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="menu" title="Файл с данными меню">
    <input type="submit" >
</form>

templates/static.html
{% extends "base.html" %}

{% block root_section %}
    <div class="container">
        {% block content %}
            <br/><pre class="text-center">Здесь должны располагаться внутренности статического раздела.</pre>
        {% endblock %}
    </div>
{% endblock %}